/* keys.c — SDL scancodes to libretro keys.
 *
 * DOSBox wants keys the way libretro names them, which is SDL 1's
 * numbering: letters and punctuation as ASCII, the rest counted up from
 * 256.  The table is by physical position (SDL scancodes), not by what
 * the key produces, so a French keyboard sends DOS the key where Q is
 * printed and DOSBox's own layout setting decides what that means -
 * exactly what the 8042 did. */
#include "internal.h"
/* The header is vendored from libretro-common as it ships; it predates
 * -Wstrict-prototypes and is not ours to edit. */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-prototypes"
#include "libretro.h"
#pragma GCC diagnostic pop
#include <SDL3/SDL_scancode.h>

// clang-format off
static const unsigned short RETROK_OF_SDL[SDL_SCANCODE_COUNT] = {
    [SDL_SCANCODE_A] = RETROK_a, [SDL_SCANCODE_B] = RETROK_b, [SDL_SCANCODE_C] = RETROK_c,
    [SDL_SCANCODE_D] = RETROK_d, [SDL_SCANCODE_E] = RETROK_e, [SDL_SCANCODE_F] = RETROK_f,
    [SDL_SCANCODE_G] = RETROK_g, [SDL_SCANCODE_H] = RETROK_h, [SDL_SCANCODE_I] = RETROK_i,
    [SDL_SCANCODE_J] = RETROK_j, [SDL_SCANCODE_K] = RETROK_k, [SDL_SCANCODE_L] = RETROK_l,
    [SDL_SCANCODE_M] = RETROK_m, [SDL_SCANCODE_N] = RETROK_n, [SDL_SCANCODE_O] = RETROK_o,
    [SDL_SCANCODE_P] = RETROK_p, [SDL_SCANCODE_Q] = RETROK_q, [SDL_SCANCODE_R] = RETROK_r,
    [SDL_SCANCODE_S] = RETROK_s, [SDL_SCANCODE_T] = RETROK_t, [SDL_SCANCODE_U] = RETROK_u,
    [SDL_SCANCODE_V] = RETROK_v, [SDL_SCANCODE_W] = RETROK_w, [SDL_SCANCODE_X] = RETROK_x,
    [SDL_SCANCODE_Y] = RETROK_y, [SDL_SCANCODE_Z] = RETROK_z,
    [SDL_SCANCODE_1] = RETROK_1, [SDL_SCANCODE_2] = RETROK_2, [SDL_SCANCODE_3] = RETROK_3,
    [SDL_SCANCODE_4] = RETROK_4, [SDL_SCANCODE_5] = RETROK_5, [SDL_SCANCODE_6] = RETROK_6,
    [SDL_SCANCODE_7] = RETROK_7, [SDL_SCANCODE_8] = RETROK_8, [SDL_SCANCODE_9] = RETROK_9,
    [SDL_SCANCODE_0] = RETROK_0,
    [SDL_SCANCODE_RETURN] = RETROK_RETURN,         [SDL_SCANCODE_ESCAPE] = RETROK_ESCAPE,
    [SDL_SCANCODE_BACKSPACE] = RETROK_BACKSPACE,   [SDL_SCANCODE_TAB] = RETROK_TAB,
    [SDL_SCANCODE_SPACE] = RETROK_SPACE,           [SDL_SCANCODE_MINUS] = RETROK_MINUS,
    [SDL_SCANCODE_EQUALS] = RETROK_EQUALS,         [SDL_SCANCODE_LEFTBRACKET] = RETROK_LEFTBRACKET,
    [SDL_SCANCODE_RIGHTBRACKET] = RETROK_RIGHTBRACKET,
    [SDL_SCANCODE_BACKSLASH] = RETROK_BACKSLASH,
    [SDL_SCANCODE_NONUSHASH] = RETROK_BACKSLASH,
    [SDL_SCANCODE_SEMICOLON] = RETROK_SEMICOLON,
    [SDL_SCANCODE_APOSTROPHE] = RETROK_QUOTE,      [SDL_SCANCODE_GRAVE] = RETROK_BACKQUOTE,
    [SDL_SCANCODE_COMMA] = RETROK_COMMA,           [SDL_SCANCODE_PERIOD] = RETROK_PERIOD,
    [SDL_SCANCODE_SLASH] = RETROK_SLASH,           [SDL_SCANCODE_CAPSLOCK] = RETROK_CAPSLOCK,
    [SDL_SCANCODE_F1] = RETROK_F1,   [SDL_SCANCODE_F2] = RETROK_F2,   [SDL_SCANCODE_F3] = RETROK_F3,
    [SDL_SCANCODE_F4] = RETROK_F4,   [SDL_SCANCODE_F5] = RETROK_F5,   [SDL_SCANCODE_F6] = RETROK_F6,
    [SDL_SCANCODE_F7] = RETROK_F7,   [SDL_SCANCODE_F8] = RETROK_F8,   [SDL_SCANCODE_F9] = RETROK_F9,
    [SDL_SCANCODE_F10] = RETROK_F10, [SDL_SCANCODE_F11] = RETROK_F11,
    [SDL_SCANCODE_F12] = RETROK_F12,
    [SDL_SCANCODE_PRINTSCREEN] = RETROK_PRINT,     [SDL_SCANCODE_SCROLLLOCK] = RETROK_SCROLLOCK,
    [SDL_SCANCODE_PAUSE] = RETROK_PAUSE,           [SDL_SCANCODE_INSERT] = RETROK_INSERT,
    [SDL_SCANCODE_HOME] = RETROK_HOME,             [SDL_SCANCODE_PAGEUP] = RETROK_PAGEUP,
    [SDL_SCANCODE_DELETE] = RETROK_DELETE,         [SDL_SCANCODE_END] = RETROK_END,
    [SDL_SCANCODE_PAGEDOWN] = RETROK_PAGEDOWN,     [SDL_SCANCODE_RIGHT] = RETROK_RIGHT,
    [SDL_SCANCODE_LEFT] = RETROK_LEFT,             [SDL_SCANCODE_DOWN] = RETROK_DOWN,
    [SDL_SCANCODE_UP] = RETROK_UP,                 [SDL_SCANCODE_NUMLOCKCLEAR] = RETROK_NUMLOCK,
    [SDL_SCANCODE_KP_DIVIDE] = RETROK_KP_DIVIDE,   [SDL_SCANCODE_KP_MULTIPLY] = RETROK_KP_MULTIPLY,
    [SDL_SCANCODE_KP_MINUS] = RETROK_KP_MINUS,     [SDL_SCANCODE_KP_PLUS] = RETROK_KP_PLUS,
    [SDL_SCANCODE_KP_ENTER] = RETROK_KP_ENTER,     [SDL_SCANCODE_KP_PERIOD] = RETROK_KP_PERIOD,
    [SDL_SCANCODE_KP_0] = RETROK_KP0, [SDL_SCANCODE_KP_1] = RETROK_KP1,
    [SDL_SCANCODE_KP_2] = RETROK_KP2, [SDL_SCANCODE_KP_3] = RETROK_KP3,
    [SDL_SCANCODE_KP_4] = RETROK_KP4, [SDL_SCANCODE_KP_5] = RETROK_KP5,
    [SDL_SCANCODE_KP_6] = RETROK_KP6, [SDL_SCANCODE_KP_7] = RETROK_KP7,
    [SDL_SCANCODE_KP_8] = RETROK_KP8,
    [SDL_SCANCODE_KP_9] = RETROK_KP9, [SDL_SCANCODE_NONUSBACKSLASH] = RETROK_OEM_102,
    [SDL_SCANCODE_LCTRL] = RETROK_LCTRL,   [SDL_SCANCODE_LSHIFT] = RETROK_LSHIFT,
    [SDL_SCANCODE_LALT] = RETROK_LALT,     [SDL_SCANCODE_RCTRL] = RETROK_RCTRL,
    [SDL_SCANCODE_RSHIFT] = RETROK_RSHIFT, [SDL_SCANCODE_RALT] = RETROK_RALT,
};
// clang-format on

unsigned dosbox_retrok_of_sdl(int sc) {
    return (sc >= 0 && sc < SDL_SCANCODE_COUNT) ? RETROK_OF_SDL[sc] : 0;
}
