# Bake text files into C string constants.  Run by CMake at build time:
#
#   cmake -DOUT=<header> -DFILES=<a.frag>,<b.frag> -P tools/embed.cmake
#
# FILES is comma-separated: a CMake list's ';' does not survive a command
# line.
#
# Each file becomes `static const char shader_<name>[]`, where <name> is the
# file name with '.' and '-' turned into '_' (composite.frag ->
# shader_composite_frag).  One string literal per source line, so a compile
# error from the GL driver still names the line it means.
if(NOT OUT OR NOT FILES)
    message(FATAL_ERROR "embed.cmake: OUT and FILES are required")
endif()
string(REPLACE "," ";" FILES "${FILES}")
set(text "/* generated by tools/embed.cmake from shaders/ - do not edit */\n#ifndef DXM_SHADERS_H\n#define DXM_SHADERS_H\n")
foreach(f IN LISTS FILES)
    get_filename_component(name "${f}" NAME)
    string(REGEX REPLACE "[.-]" "_" sym "${name}")
    file(READ "${f}" body)
    string(APPEND text "\n/* ${name} */\nstatic const char shader_${sym}[] =\n")
    string(REGEX REPLACE "\n$" "" body "${body}")
    string(REPLACE "\\" "\\\\" body "${body}")
    string(REPLACE "\"" "\\\"" body "${body}")
    string(REPLACE "\n" "\\n\"\n\"" body "${body}")
    string(APPEND text "\"${body}\\n\";\n")
endforeach()
string(APPEND text "\n#endif\n")
file(WRITE "${OUT}" "${text}")
