#!/usr/bin/env python3
"""mkbanners.py <out.c> <out.h> <in.jpg>...
Bake the SETUP banners into the program as the files themselves.

Nothing is decoded here.  The artwork is 640x240 and the machine shows it
one pixel for one, but as pixels it is 150 KB apiece and over a megabyte
all told, where the same nine as JPEG are a third of that.  So the bytes go
in whole and the machine opens them when it needs one (src/setup/banner.c):
the fade, the lift and the trim that used to be baked happen there, along
with the fitting of a palette, because a 256-colour screen needs one and
the file has not got one.

That also means this tool needs no image library, which is the reason the
rest of tools/ has none either."""
import sys

W, H = 640, 240  # what every banner is drawn at; the loader checks


def main():
    out_c, out_h, srcs = sys.argv[1], sys.argv[2], sys.argv[3:]
    names = []
    with open(out_c, 'w') as f:
        f.write("/* generated by tools/mkbanners.py from assets/banners - do not edit */\n")
        f.write('#include "banners.h"\n')
        for src in srcs:
            name = src.split('/')[-1].rsplit('.', 1)[0]
            data = open(src, 'rb').read()
            names.append((name, len(data)))
            f.write(f"\nstatic const uint8_t file_{name}[] = {{")
            f.write(','.join(str(b) for b in data))
            f.write("};\n")
        f.write("\nconst dxm_banner dxm_banners[] = {\n")
        for name, n in names:
            f.write(f'    {{"{name}", file_{name}, {n}}},\n')
        f.write("};\n")
        f.write(f"const int dxm_banner_count = {len(names)};\n")

    with open(out_h, 'w') as f:
        f.write("/* generated by tools/mkbanners.py from assets/banners - do not edit */\n")
        f.write("#ifndef DXM_BANNERS_H_INCLUDED\n#define DXM_BANNERS_H_INCLUDED\n")
        f.write("#include <stddef.h>\n#include <stdint.h>\n")
        f.write(f"#define DXM_BANNER_W {W}\n#define DXM_BANNER_H {H}\n")
        f.write("/* one piece of artwork, as the file it was made as: JPEG or PNG,\n"
                " * opened by src/setup/banner.c when the machine wants it */\n")
        f.write("typedef struct {\n    const char *name;\n    const uint8_t *file;\n"
                "    size_t len;\n} dxm_banner;\n")
        f.write("extern const dxm_banner dxm_banners[];\nextern const int dxm_banner_count;\n")
        f.write("#endif\n")


main()
