#!/usr/bin/env python3
"""mkbdf.py <in.bdf> <symbol> <out.h> [first] [last]
Bake an X11 bitmap font into a C table: a proportional face for the
machine's own programs, where the character generator's eight-column cells
read as a terminal.

BDF is a text format - one STARTCHAR block per glyph, the bitmap in hex
rows, the box it sits in given by BBX as width, height and the offset of
its bottom left corner from the origin.  That offset is the whole point of
a proportional font and is kept: a comma hangs below the line, a quote
sits at the top, and both advance by their own width rather than a cell's.

Only the printable ASCII range is taken.  Anything else the machine draws -
the arrows, the marks - it already has in the VGA face."""
import sys

src, sym, out = sys.argv[1], sys.argv[2], sys.argv[3]
first = int(sys.argv[4]) if len(sys.argv) > 4 else 32
last = int(sys.argv[5]) if len(sys.argv) > 5 else 126

glyphs = {}          # code -> (w, h, xoff, yoff, advance, rows)
ascent = descent = 0
code = None
bbx = dwidth = None
rows = None

for line in open(src, encoding='latin-1'):
    word = line.split()
    if not word:
        continue
    if word[0] == 'FONT_ASCENT':
        ascent = int(word[1])
    elif word[0] == 'FONT_DESCENT':
        descent = int(word[1])
    elif word[0] == 'ENCODING':
        code = int(word[1])
    elif word[0] == 'DWIDTH':
        dwidth = int(word[1])
    elif word[0] == 'BBX':
        bbx = tuple(int(v) for v in word[1:5])
    elif word[0] == 'BITMAP':
        rows = []
    elif word[0] == 'ENDCHAR':
        if code is not None and first <= code <= last and bbx and rows is not None:
            w, h, xoff, yoff = bbx
            stride = (w + 7) // 8
            flat = []
            for r in rows:
                v = int(r, 16) if r else 0
                b = v.to_bytes(max(stride, (len(r) + 1) // 2), 'big')
                flat.extend(b[:stride] if stride else [])
            glyphs[code] = (w, h, xoff, yoff, dwidth, flat)
        code, bbx, rows = None, None, None
    elif rows is not None:
        rows.append(word[0])

if not glyphs:
    sys.exit(f"{src}: no glyphs in {first}..{last}")

data, index = [], {}
for c in range(first, last + 1):
    if c not in glyphs:
        glyphs[c] = (0, 0, 0, 0, glyphs.get(32, (0, 0, 0, 0, 4, []))[4], [])
    w, h, xoff, yoff, adv, flat = glyphs[c]
    index[c] = (len(data), w, h, xoff, yoff, adv)
    data.extend(flat)

with open(out, 'w') as f:
    up = sym.upper()
    f.write(f"/* generated by tools/mkbdf.py from {src.split('/')[-1]} - do not edit */\n")
    f.write(f"#ifndef {up}_H_INCLUDED\n#define {up}_H_INCLUDED\n#include <stdint.h>\n")
    f.write(f"#define {up}_FIRST {first}\n#define {up}_LAST {last}\n")
    f.write(f"#define {up}_ASCENT {ascent}\n#define {up}_DESCENT {descent}\n")
    f.write("/* One glyph: where its rows start in the bitmap, the box they fill,\n"
            " * where that box sits against the origin, and how far the pen moves.\n"
            " * Rows are (w+7)/8 bytes, most significant bit leftmost.  Shared by\n"
            " * every face baked by this tool, so it is declared once. */\n")
    f.write("#ifndef DXM_GLYPH_DEFINED\n#define DXM_GLYPH_DEFINED\n")
    f.write("typedef struct {\n    uint16_t at;\n    uint8_t w, h, adv;\n"
            "    int8_t xoff, yoff;\n} dxm_glyph;\n#endif\n")
    f.write(f"static const dxm_glyph {sym}_glyphs[] = {{\n")
    for c in range(first, last + 1):
        at, w, h, xoff, yoff, adv = index[c]
        f.write(f"    {{{at},{w},{h},{adv},{xoff},{yoff}}}, /* {chr(c) if c != 92 else chr(92)*2} */\n")
    f.write("};\n")
    f.write(f"static const uint8_t {sym}_bits[] = {{")
    f.write(','.join(str(b) for b in data) if data else '0')
    f.write("};\n#endif\n")

print(f"{out}: {len(glyphs)} glyphs, {len(data)} bytes, ascent {ascent} descent {descent}")
