#!/usr/bin/env python3
"""Bake a uuencoded console font into a C table.

    mkfont.py <font.uu> <symbol> <out.h>

The font is 256 glyphs of 16 rows, one byte per row, MSB the leftmost
pixel - the raw VGA character-generator layout, which is how FreeBSD keeps
its console fonts."""
import sys

src, sym, out = sys.argv[1:4]
data = bytearray()
with open(src, "rb") as f:
    for line in f:
        if line.startswith((b"begin", b"end")) or not line.strip():
            continue
        # a line carries (first char - 32) bytes, four characters to three
        # bytes.  FreeBSD's encoder leaves live bits in the padding of a
        # short last group, which the standard library refuses, so unpack
        # by hand.
        n = (line[0] - 32) & 63
        v = [(c - 32) & 63 for c in line[1:1 + (n + 2) // 3 * 4]]
        grp = bytearray()
        for k in range(0, len(v), 4):
            a, b, c, d = v[k:k + 4]
            grp += bytes(((a << 2 | b >> 4) & 255, (b << 4 | c >> 2) & 255, (c << 6 | d) & 255))
        data += grp[:n]
data = bytes(data[:4096]) + bytes(4096 - min(len(data), 4096))

with open(out, "w") as f:
    f.write("/* generated by tools/mkfont.py from %s - do not edit.\n" % src)
    f.write(" * The VGA 8x16 code page 437 font, glyph for glyph the one a VGA card's\n")
    f.write(" * character generator held, from FreeBSD's share/syscons/fonts (BSD\n")
    f.write(" * licence).  256 glyphs, 16 rows each, MSB = leftmost pixel. */\n")
    f.write("static const uint8_t %s[256][16] = {\n" % sym)
    for ch in range(256):
        rows = data[ch * 16:(ch + 1) * 16]
        f.write("    {%s}, /* %02X */\n" % (", ".join("0x%02X" % b for b in rows), ch))
    f.write("};\n")
