#!/usr/bin/env python3
"""mkkeys.py <in.wav> <symbol> <out.h> [--wav audition.wav]

Cut a recording of someone typing on a mechanical keyboard into single key
strokes, and bake the clean ones into a C header: one array of s16 samples
and the offsets where each stroke starts.

A stroke is the switch's click, the keycap bottoming out ten or twenty
milliseconds later, and a ring that has died to about -30 dB by forty.  In
real typing the next thing - this key coming back up, or the next one going
down - arrives anywhere from twenty-five milliseconds on, so each stroke is cut
at whichever comes first: the next rise, or 80 ms.  A stroke with something
still ringing into its start, or cut short of 40 ms by the next key, is left
out; so is anything too soft to be a key going down, which is a release.

Integers throughout, so the output is the same bytes on every machine and
tools/regen.sh --check can hold it to that.

--wav writes the strokes out spaced apart, to listen to what was chosen.
"""
import struct
import sys
import wave

src, sym, out = sys.argv[1], sys.argv[2], sys.argv[3]
audition = sys.argv[5] if len(sys.argv) > 5 and sys.argv[4] == "--wav" else None

w = wave.open(src)
assert w.getnchannels() == 1 and w.getsampwidth() == 2, "want mono s16"
sr = w.getframerate()
n = w.getnframes()
x = struct.unpack(f"<{n}h", w.readframes(n))
MS = sr // 1000

# Onsets, from the energy of the first difference in 1 ms frames: the
# difference is a crude high-pass, which is where a click lives, and it keeps
# a stroke's body from blurring where the next one starts.
d = [0] + [x[i] - x[i - 1] for i in range(1, n)]
E = [sum(v * v for v in d[i : i + MS]) for i in range(0, n - MS, MS)]
top = max(E)
onsets = []
for t in range(15, len(E)):
    if E[t] * 100 < top:  # quieter than -20 dB of the loudest
        continue
    if E[t] * 100 < min(E[t - 15 : t]) * 1585:  # not 12 dB over what was before
        continue
    if onsets and t - onsets[-1] < 25:
        continue
    onsets.append(t)


def e5(ms):
    """the plain signal's energy over the 5 ms from `ms`"""
    return sum(v * v for v in x[ms * MS : (ms + 5) * MS])


strokes = []
for i, t in enumerate(onsets):
    if max(E[t : t + 6]) * 1000 < top * 126:  # softer than -9 dB: a key coming up
        continue
    if max(E[t - 12 : t - 2]) * 1000 > top * 2:  # the last one still ringing
        continue
    peak = max(e5(t), e5(t + 5))
    end = t + 80
    if i + 1 < len(onsets):
        end = min(end, onsets[i + 1] - 2)
    for k in range(t + 25, end, 5):
        # 6 dB over the window before it, and within 30 dB of the stroke
        if e5(k) * 100 >= e5(k - 5) * 398 and e5(k) * 1000 >= peak:
            end = k
            break
    if end - t < 40:
        continue
    strokes.append((t - 2, end))

# Each stroke cut out, faded in over its 2 ms of lead-in and out over its
# last 10, and brought to the same peak: how hard a key is struck is for the
# player to vary, not something to inherit from one take.
FULL = 20000
pcm, at = [], [0]
for a, b in strokes:
    s = list(x[a * MS : b * MS])
    fi, fo = 2 * MS, 10 * MS
    for j in range(fi):  # smoothstep, t*t*(3-2t), in integers
        s[j] = s[j] * j * j * (3 * fi - 2 * j) // (fi * fi * fi)
    for j in range(fo):
        k = fo - j
        s[len(s) - fo + j] = s[len(s) - fo + j] * k * k * (3 * fo - 2 * k) // (fo * fo * fo)
    pk = max(abs(v) for v in s)
    s = [(1 if v >= 0 else -1) * ((abs(v) * FULL + pk // 2) // pk) for v in s]
    pcm += s
    at.append(len(pcm))

U = sym.upper()
with open(out, "w") as f:
    f.write("/* generated by tools/mkkeys.py - do not edit */\n")
    f.write(f"#ifndef {U}_H\n#define {U}_H\n#include <stdint.h>\n")
    f.write(f"#define {U}_RATE {sr}\n")
    f.write(f"#define {U}_N {len(strokes)}\n")
    f.write(f"/* stroke k is {sym}[{sym}_at[k]] up to {sym}[{sym}_at[k + 1]] */\n")
    f.write(f"static const int {sym}_at[{len(at)}] = {{" + ", ".join(map(str, at)) + "};\n")
    f.write(f"static const int16_t {sym}[{len(pcm)}] = {{\n")
    for i in range(0, len(pcm), 16):
        f.write("  " + ",".join(str(v) for v in pcm[i : i + 16]) + ",\n")
    f.write("};\n#endif\n")

if audition:
    gap = [0] * (sr // 4)
    a = wave.open(audition, "wb")
    a.setnchannels(1)
    a.setsampwidth(2)
    a.setframerate(sr)
    for k in range(len(strokes)):
        a.writeframes(struct.pack(f"<{at[k + 1] - at[k]}h", *pcm[at[k] : at[k + 1]]))
        a.writeframes(struct.pack(f"<{len(gap)}h", *gap))
    a.close()

lens = ", ".join(f"{(b - a)}" for a, b in strokes)
print(f"{out}: {len(strokes)} strokes of {lens} ms, {len(pcm)} samples", file=sys.stderr)
