#!/usr/bin/env python3
"""mklogo.py <in.png> <symbol> <out.h>
Bake an RGB PNG into a C array, keying out the white background to alpha so
it composites onto the black POST screen."""
import sys, zlib, struct
src, sym, out = sys.argv[1], sys.argv[2], sys.argv[3]
d = open(src,'rb').read(); pos = 8; idat=b''
while pos < len(d):
    ln, = struct.unpack('>I', d[pos:pos+4]); typ = d[pos+4:pos+8]
    ch = d[pos+8:pos+8+ln]
    if typ == b'IHDR':
        w,h,bd,ct,_,_,inter = struct.unpack('>IIBBBBB', ch)
    elif typ == b'IDAT': idat += ch
    pos += 12+ln
assert bd==8 and inter==0, "expect 8-bit non-interlaced"
bpp = {0:1,2:3,3:1,4:2,6:4}[ct]
raw = zlib.decompress(idat); stride = w*bpp
img = bytearray(h*stride); prev = bytearray(stride); p=0
for y in range(h):
    f = raw[p]; p+=1
    line = bytearray(raw[p:p+stride]); p+=stride
    if f==1:
        for i in range(bpp,stride): line[i]=(line[i]+line[i-bpp])&255
    elif f==2:
        for i in range(stride): line[i]=(line[i]+prev[i])&255
    elif f==3:
        for i in range(stride):
            a=line[i-bpp] if i>=bpp else 0
            line[i]=(line[i]+((a+prev[i])>>1))&255
    elif f==4:
        for i in range(stride):
            a=line[i-bpp] if i>=bpp else 0
            b=prev[i]; c=prev[i-bpp] if i>=bpp else 0
            pp=a+b-c; pa=abs(pp-a); pb=abs(pp-b); pc=abs(pp-c)
            pr = a if (pa<=pb and pa<=pc) else (b if pb<=pc else c)
            line[i]=(line[i]+pr)&255
    img[y*stride:(y+1)*stride]=line; prev=line
# RGBA out, white -> transparent
px=[]
for y in range(h):
    for x in range(w):
        o=y*stride+x*bpp
        if ct==2:   r,g,b = img[o],img[o+1],img[o+2]
        elif ct==6: r,g,b = img[o],img[o+1],img[o+2]
        elif ct==0: r=g=b = img[o]
        else:       r=g=b = img[o]
        if ct in (4,6):
            # The PNG carries its own alpha - USE IT.  Deriving transparency
            # from brightness instead erases white text, which is exactly
            # what a light wordmark on a transparent background is.
            a = img[o+ (1 if ct==4 else 3)]
        else:
            lum=(r*299+g*587+b*114)//1000
            a = 0 if lum>=242 else (255 if lum<=225 else int((242-lum)*255/17))
        px.append((r,g,b,a))
with open(out,'w') as f:
    f.write("/* generated by tools/mklogo.py - do not edit */\n")
    f.write(f"#ifndef {sym.upper()}_H_INCLUDED\n#define {sym.upper()}_H_INCLUDED\n#include <stdint.h>\n")
    f.write(f"#define {sym.upper()}_W {w}\n#define {sym.upper()}_HT {h}\n")
    f.write(f"static const uint8_t {sym}[{w*h*4}] = {{\n")
    flat=[c for q in px for c in q]
    for i in range(0,len(flat),24):
        f.write("  "+",".join(str(v) for v in flat[i:i+24])+",\n")
    f.write("};\n#endif\n")
print(f"{out}: {w}x{h}")
