#!/usr/bin/env python3
"""mkpcm.py <in.raw> <symbol> <out.h> — bake s16 mono PCM into a C array."""
import sys, struct
raw, sym, out = sys.argv[1], sys.argv[2], sys.argv[3]
d = open(raw,'rb').read(); n = len(d)//2
v = struct.unpack(f'<{n}h', d[:n*2])
with open(out,'w') as f:
    f.write(f"/* generated by tools/mkpcm.py - do not edit */\n")
    f.write(f"#ifndef {sym.upper()}_H\n#define {sym.upper()}_H\n#include <stdint.h>\n")
    f.write(f"#define {sym.upper()}_LEN {n}\n")
    f.write(f"#define {sym.upper()}_RATE 22050\n")
    f.write(f"static const int16_t {sym}[{n}] = {{\n")
    for i in range(0,n,16):
        f.write("  "+",".join(str(x) for x in v[i:i+16])+",\n")
    f.write("};\n#endif\n")
print(f"{out}: {n} samples")
