#!/usr/bin/env python3
"""mksplash.py <in.png> <symbol> <out.c> <out.h> [max_width]

Bake a large RGBA PNG into a C translation unit for the startup splash.

Unlike mklogo.py this does NOT emit a flat array in a header: the splash is
two orders of magnitude bigger than the POST logo, and a multi-megabyte
header would be re-parsed on every rebuild of whatever includes it.  The
data goes into its own .c file (compiled once, then just linked) and is
run-length encoded, which the image is extremely well suited to - most of a
wordmark is empty space.

Colour is stored PREMULTIPLIED by alpha.  The splash is drawn scaled up with
linear filtering, and straight alpha would pull the transparent pixels'
black RGB into every edge as a dark fringe.
"""
import sys, zlib, struct

src, sym, out_c, out_h = sys.argv[1:5]
maxw = int(sys.argv[5]) if len(sys.argv) > 5 else 1024

# ---- decode the PNG ------------------------------------------------------
d = open(src, 'rb').read()
pos, idat = 8, b''
while pos < len(d):
    ln, = struct.unpack('>I', d[pos:pos+4]); typ = d[pos+4:pos+8]
    ch = d[pos+8:pos+8+ln]
    if typ == b'IHDR':
        w, h, bd, ct, _, _, inter = struct.unpack('>IIBBBBB', ch)
    elif typ == b'IDAT':
        idat += ch
    pos += 12 + ln
assert bd == 8 and inter == 0, "expect 8-bit non-interlaced"
assert ct in (2, 6), "expect RGB or RGBA"
bpp = 4 if ct == 6 else 3
raw = zlib.decompress(idat); stride = w * bpp
img = bytearray(h * stride); prev = bytearray(stride); p = 0
for y in range(h):
    f = raw[p]; p += 1
    line = bytearray(raw[p:p+stride]); p += stride
    if f == 1:
        for i in range(bpp, stride): line[i] = (line[i] + line[i-bpp]) & 255
    elif f == 2:
        for i in range(stride): line[i] = (line[i] + prev[i]) & 255
    elif f == 3:
        for i in range(stride):
            a = line[i-bpp] if i >= bpp else 0
            line[i] = (line[i] + ((a + prev[i]) >> 1)) & 255
    elif f == 4:
        for i in range(stride):
            a = line[i-bpp] if i >= bpp else 0
            b = prev[i]; c = prev[i-bpp] if i >= bpp else 0
            pp = a + b - c; pa = abs(pp-a); pb = abs(pp-b); pc = abs(pp-c)
            pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
            line[i] = (line[i] + pr) & 255
    img[y*stride:(y+1)*stride] = line; prev = line

# ---- box-downscale, averaging in premultiplied space ---------------------
nw = min(w, maxw)
nh = max(1, round(h * nw / w))
px = bytearray(nw * nh * 4)
for y in range(nh):
    y0 = y * h // nh; y1 = max(y0 + 1, (y + 1) * h // nh)
    for x in range(nw):
        x0 = x * w // nw; x1 = max(x0 + 1, (x + 1) * w // nw)
        sr = sg = sb = sa = n = 0
        for yy in range(y0, y1):
            for xx in range(x0, x1):
                o = yy * stride + xx * bpp
                a = img[o+3] if bpp == 4 else 255
                sr += img[o] * a; sg += img[o+1] * a; sb += img[o+2] * a
                sa += a; n += 1
        o = (y * nw + x) * 4
        # premultiplied: (colour * alpha) averaged, then divided by the
        # sample count - NOT by the alpha sum, which would un-premultiply
        px[o]   = sr // (255 * n)
        px[o+1] = sg // (255 * n)
        px[o+2] = sb // (255 * n)
        px[o+3] = sa // n

# ---- run-length encode: u16 count, then the 4 pixel bytes ----------------
enc = bytearray(); i = 0; total = nw * nh
while i < total:
    j = i + 1
    while j < total and j - i < 65535 and px[j*4:j*4+4] == px[i*4:i*4+4]:
        j += 1
    c = j - i
    enc += bytes([c & 255, c >> 8]) + px[i*4:i*4+4]
    i = j

G = sym.upper()
with open(out_h, 'w') as f:
    f.write("/* generated by tools/mksplash.py - do not edit */\n")
    f.write(f"#ifndef {G}_H_INCLUDED\n#define {G}_H_INCLUDED\n")
    f.write("#include <stdint.h>\n")
    f.write(f"#define {G}_W  {nw}\n#define {G}_HT {nh}\n")
    f.write(f"/* Decodes the baked RLE into a {nw}*{nh} PREMULTIPLIED RGBA\n"
            " * buffer.  Caller frees. */\n")
    f.write(f"uint8_t *{sym}_rgba(void);\n#endif\n")

with open(out_c, 'w') as f:
    f.write("/* generated by tools/mksplash.py - do not edit */\n")
    f.write(f'#include "{out_h.rsplit("/",1)[-1]}"\n#include <stdlib.h>\n\n')
    f.write(f"/* run-length encoded: u16 count little-endian, then RGBA */\n")
    f.write(f"static const uint8_t {sym}_rle[{len(enc)}] = {{\n")
    for k in range(0, len(enc), 20):
        f.write(" " + "".join("%d," % b for b in enc[k:k+20]) + "\n")
    f.write("};\n\n")
    f.write(f"""uint8_t *{sym}_rgba(void){{
    uint8_t *out = malloc((size_t){G}_W * {G}_HT * 4);
    if (!out) return 0;
    size_t o = 0;
    for (size_t i = 0; i + 6 <= sizeof {sym}_rle; i += 6) {{
        unsigned n = {sym}_rle[i] | ({sym}_rle[i+1] << 8);
        while (n--) {{
            out[o++] = {sym}_rle[i+2]; out[o++] = {sym}_rle[i+3];
            out[o++] = {sym}_rle[i+4]; out[o++] = {sym}_rle[i+5];
        }}
    }}
    return out;
}}
""")
print(f"{sym}: {w}x{h} -> {nw}x{nh}, {len(enc)} bytes RLE "
      f"({100.0*len(enc)/(nw*nh*4):.0f}% of raw)")
