/* generated by tools/mksplash.py - do not edit */
#ifndef DXM_SPLASH_H_INCLUDED
#define DXM_SPLASH_H_INCLUDED
#include <stdint.h>
#define DXM_SPLASH_W  1024
#define DXM_SPLASH_HT 409
/* Decodes the baked RLE into a 1024*409 PREMULTIPLIED RGBA
 * buffer.  Caller frees. */
uint8_t *dxm_splash_rgba(void);
#endif
